#pragma once
#include "CoreMinimal.h"

const TArray<FString> HardHeterograms = 
{
    TEXT("background"),
    TEXT("regulations"),
    TEXT("compatible"),
    TEXT("regulation"),
    TEXT("previously"),
    TEXT("importance"),
    TEXT("authorized"),
    TEXT("switzerland"),
    TEXT("milfhunter"),
    TEXT("purchasing"),
    TEXT("bankruptcy"),
    TEXT("republican"),
    TEXT("complaints"),
    TEXT("customized"),
    TEXT("personality"),
    TEXT("complexity"),
    TEXT("documentary"),
    TEXT("algorithms"),
    TEXT("boundaries"),
    TEXT("soundtrack"),
    TEXT("thumbnails"),
    TEXT("scheduling"),
    TEXT("copyrights"),
    TEXT("decorating"),
    TEXT("configured"),
    TEXT("journalism"),
    TEXT("charleston"),
    TEXT("completing"),
    TEXT("copyrighted"),
    TEXT("backgrounds"),
    TEXT("volkswagen"),
    TEXT("republicans"),
    TEXT("productive"),
    TEXT("uzbekistan"),
    TEXT("introduces"),
    TEXT("atmospheric"),
    TEXT("journalist"),
    TEXT("demographic"),
    TEXT("reductions")
};